import pandas as pd
import mysql.connector
conn=mysql.connector.connect(
    host="localhost",
    user="root",
    password="sandhya@1402",
    database="testing_mysql_connection"
)
print("connection done")
# database=company
# cursor=conn.cursor()
# cursor.execute("SHOW DATABASES")
# for db in cursor:
#      print(db)
# s=cursor.fetchall()
# for db in s:
    # print(db)
# cursor.execute("create table customer (id int,name varchar(20))")
cursor=conn.cursor()
# cursor.execute("USE testing_mysql_connection ")
cursor.execute("SHOW DATABASES")
# print("executed")     
a=cursor.fetchone()
print(a)
# print(type(a))
# print(len(a))
# print(a[0][0])
# for i in range(len(a)):
    # print(a[i][0])
# # cursor.execute("create database testing_mysql_connection IF NOT EXISTS")
# print("database created")
# cursor.execute("use testing_mysql_connection")
# cursor.execute("SHOW tables")
# tables=cursor.fetchall()
# print(tables)
# cursor.execute("CREATE TABLE students(id int,name varchar(50),marks int)")
# print("created a table")
# tables=cursor.fetchall()
# print(tables)
# cursor.execute("desc students")
# data=cursor.fetchall()
# print(data)
# cursor.execute("insert into students values(1,'sandhya',90)")
# cursor.execute("select * from students")
# details=cursor.fetchall()
# print(details)
# cursor.execute("insert into students values(2,'harish',56),(3,'sujay',65)")
# cursor.execute("select * from students")
# details=cursor.fetchall()
# print(details)
# sql = "INSERT INTO students VALUES(%s,%s,%s)"
# values=(4,"vinu",65)
# cursor.execute(sql,values)
# conn.commit()
# cursor.execute("select * from students")
# d=cursor.fetchall()
# print(d)
# query="select * from students"
# s=pd.read_sql(query,conn)
# print(s)   
# sql="INSERT INTO students values(%s,%s,%s)"
# values=(5,'sinchu',65)
# cursor.execute(sql,values)
# conn.commit()
# cursor.execute("select * from students")
# detail=cursor.fetchall()
# print(detail)
# cursor.execute("""delete from students
# where id=5""")
# cursor.execute("select * from students")
# data=cursor.fetchall()
# print(data)
# conn.commit()
# cursor.execute("insert into students values(1,'lavin',89),(2,'manisha',55),(3,'lakshmi',45)")
# cursor.execute("select * from students")
# d=cursor.fetchall()
# print(d)
# conn.commit()
# cursor.execute("truncate table students")
# cursor.execute("select * from students")
# d=cursor.fetchall()
# print(d)
# conn.commit()
# cursor.execute("""insert into students values(1,'sandhya',65),(2,'vinu',55),(3,'harish',78),
# (4,'lakshmi',78)""")
# cursor.execute("select * from students")
# print(cursor.fetchall())
# conn.commit()
# print(cursor.fetchone())
# cursor.execute("""update students
# set marks=98
# where id=1""")
# conn.commit()
# cursor.execute("select * from students")
# print(cursor.fetchone())
